#!/bin/bash
# vim: ai:ts=8:sw=8:noet
set -eufo pipefail
export SHELLOPTS
IFS=$'\t\n'

# This script needs some dependencies to run correctly, check them before start
command -v kubectl >/dev/null 2>&1 || { echo 'Please install kubectl'; exit 1; }
command -v kubedog >/dev/null 2>&1 || { echo 'Please install kubedog'; exit 1; }
command -v jq >/dev/null 2>&1 || { echo 'Please install jq'; exit 1; }


# Waits to all the workload types to be ready based on what ready means for
# kubedog (deployment pods updated, pods up and running...).
# We convert kahoy output into a kubedog multitrack cli format.
function wait_applied() 
    [[ $# -ne 2 ]] && echo "USAGE: wait_applied KAHOY_REPORT_OUTPUT TIMEOUT_SECONDS" && exit 1

    timeout="${2}"
    echo "[*] Waiting applied resources (timeout after $timeout seconds)..."
    echo "${1}" | jq '